version: "3.9"

services:
  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3
    networks:
      - app-network

  backend:
    build:
      context: backend
    ports:
      - "8666:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
volumes:
  app-db-data:
  root-home:

networks:
    app-network: